theme: jekyll-theme-minimal
title: Placebo Imaging Consortium
description: Ulrike Bingel, Tor Wager, Matthias Zunhammer, Balint Kincses, Tamas Spisak, Lauren Atlas, Fabrizio Benedetti, Christian Büchel, Jae Chan Choi, Luana Colloca, Davide Duzzi, Falk Eippert, Dan-Mikael Ellingsen, Sigrid Elsenbruch, Stephan Geuter, Helena Hartmann, Ted J. Kaptchuk, Simon S. Kessner, Irving Kirsch, Jian Kong, Claus Lamm, Siri Leknes, Alexa Müllner-Huber, Fausta Lui, Carlo A. Porro, Markus Rütgen, Lieven Schenk, Julia Schmid, Nina Theysohn, Irene Tracey, Nathalie Wrobel, and Fadel Zeidan
logo: fig/logo.png
google_analytics: UA-120757757-4
plugins:
  - jemoji
